name: ai_studio_mobile
description: "AI Studio Full Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  gal: ^2.3.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
